// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlwHx_fGuFL2yCJaUtHkkwPvGAl-fiHaE',
    appId: '1:1008557235823:web:ac2e273fac5ef181aaf79a',
    messagingSenderId: '1008557235823',
    projectId: 'mk-glab-messenger',
    authDomain: 'mk-glab-messenger.firebaseapp.com',
    storageBucket: 'mk-glab-messenger.firebasestorage.app',
    measurementId: 'G-461XT3LJD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO5YSqlXPo8M8i-3xMPlzZnyPMTvgfd3c',
    appId: '1:1008557235823:android:20577d56390b80f8aaf79a',
    messagingSenderId: '1008557235823',
    projectId: 'mk-glab-messenger',
    storageBucket: 'mk-glab-messenger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjYwTGK1ITiixjaXu2gl42PIpvIXykIMo',
    appId: '1:1008557235823:ios:1522dfeeac86b079aaf79a',
    messagingSenderId: '1008557235823',
    projectId: 'mk-glab-messenger',
    storageBucket: 'mk-glab-messenger.firebasestorage.app',
    iosBundleId: 'com.example.secureMessenger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjYwTGK1ITiixjaXu2gl42PIpvIXykIMo',
    appId: '1:1008557235823:ios:1522dfeeac86b079aaf79a',
    messagingSenderId: '1008557235823',
    projectId: 'mk-glab-messenger',
    storageBucket: 'mk-glab-messenger.firebasestorage.app',
    iosBundleId: 'com.example.secureMessenger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlwHx_fGuFL2yCJaUtHkkwPvGAl-fiHaE',
    appId: '1:1008557235823:web:99b63edeb62f47efaaf79a',
    messagingSenderId: '1008557235823',
    projectId: 'mk-glab-messenger',
    authDomain: 'mk-glab-messenger.firebaseapp.com',
    storageBucket: 'mk-glab-messenger.firebasestorage.app',
    measurementId: 'G-43FSWQR7JN',
  );
}
